### Get all notes
GET http://localhost:3001/api/notes

### Get a note by id
GET http://localhost:3001/api/notes/1

### Delete a note by id
DELETE http://localhost:3001/api/notes/1

### Create a note
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "This is a new note",
  "important": true
}       
