### Get all persons
GET http://localhost:3001/api/persons


### Get info
GET http://localhost:3001/info


### Get a person by id
GET http://localhost:3001/api/persons/1

### Get a person by id that does not exist
GET http://localhost:3001/api/persons/5


### Delete a person by id
DELETE http://localhost:3001/api/persons/1

### Delete a person by id that does not exist
DELETE http://localhost:3001/api/persons/5

### Add a person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "1234567890"
}

### Add a person with missing name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "1234567890"
}

### Add a person with missing number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe"
}

### Add a person with existing name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "040-123456"
}
